---
- name: Import schema for icingadb
  mysql_db:
    state: import
    name: "{{ icingadb_db_name }}"
    target: "{{ icingadb_db_schema }}"
  ignore_errors: yes
  when: icingadb_import_mysql_schema
