---
- name: Include OS specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - 'vars'
  tags:
    - install
    - config

- name: Include OS specific installation
  include_tasks: "icingadb_install_{{ ansible_os_family }}.yml"

- name: Include Tasks to configure Database Backend
  include_tasks: icingadb_database.yml

- name: Include Tasks to configure IcingaDB
  include_tasks: icingadb_config.yml


- name: start and enable service
  service:
    name: icingadb
    state: started
    enabled: yes


- name: start end enable icingadb-redis
  service:
    name: icingadb-redis
    state: started
    enabled: yes
