---
- name: icingadb-redis-restart
  service:
    name: "{{ icingadb_redis_service_name }}"
    state: restarted

- name: icingadb-reload
  service:
    name: "{{ icingadb_service_name }}"
    state: reloaded
