---
- name: prepare container
  hosts: all
  gather_facts: true
  vars:
    mysql_enabled_on_startup: yes
    mysql_databases:
      - name: icingadb
      - name: icinga
    mysql_users:
      - name: icinga
        password: icinga
        priv: "icinga.*:ALL"
        state: present
      - name: icingadb
        password: icingadb
        priv: "icingadb.*:ALL"
        state: present
  tasks:
    - name: apt update
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - gnupg
      when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" ) or
            ( ansible_os_family == "Debian" and ansible_distribution_major_version == "10" )
  roles:
    - mysql
